### ISSUE TITLE
RHW-2 conversion to L2 RHW-2 when crossing Diagonal L1/L2 RHW-6C/8C

### ISSUE THREAD

**Issue by TarkusSC4** [NAMTeam/Network-Addon-Mod#153]
Additionally, the conversion causes the Diagonal L1 RHW-6C/8C to block RHW crossings.

**Comment by TarkusSC4** [comment]
RHW crossings involving diagonal elevated C-type networks were disabled with prevents in NAM 31.2.  The MetaRUL update will most likely solve this one.

**Comment by jflann** [comment]
Seems resolved
