### ISSUE TITLE
El-Rail-Avenue x OWR pathing issue

### ISSUE THREAD

**Issue by memo33** [NAMTeam/Network-Addon-Mod#166]
The straight OWR tile adjacent to the intersection lacks a single paths (still functional). This is because of how El-Rail-Avenue is implemented: The underlying tile is a Road-OWR transition so that the paths of the OWR tile don't auto-reverse. The transition is overriden to the default straight OWR ID. Essentially, this would have to be replaced by a new ID with double-sided paths, but this would require special handling for OWR-1 and OWR-3+ if they ever get implemented for El-Rail-Avenue.

Alternatively, replacing the default OWR orthogonal paths by double-sided paths could work as these get auto-reversed on normal OWRs anyway, but this would need to be confirmed by testing.

![capture_20131207_235926](https://f.cloud.github.com/assets/3751999/1699349/6628382a-5f93-11e3-83d2-75b6d2332073.jpg)

**Comment by jflann** [comment]
![image](https://user-images.githubusercontent.com/26899145/122851036-eb25fd80-d2d3-11eb-92a7-a25d4e8543cf.png)

fixed
