### ISSUE TITLE
Diagonal Street Stub misorientation

### ISSUE THREAD

**Issue by TarkusSC4** [NAMTeam/Network-Addon-Mod#190]
Reported by vortext at SC4D.  The SAM diagonal stubs are occasionally misoriented.  Limited impact on functionality.

https://dl.dropbox.com/s/66vising58x6tj9/stub.jpg

**Comment by jflann** [comment]
All of the SAM variants are appearing in the correct orientation, and since the diagonal street retexture, doesn't appear to even be a cosmetic issue anymore.
