### ISSUE TITLE
New RRW Bridge, minor texture issue in Z3 S/W views.

### ISSUE THREAD

**Issue by MGB204** [NAMTeam/Network-Addon-Mod#275]
Hard to see, but in Z3, the S and W views of this bridge show an incorrectly rotated texture on the end pieces.

It's possible the issue occurs at lower zoom levels, but if it does it's too small for me to see. All other Z/R tested as fine.

![bridge-issue](https://cloud.githubusercontent.com/assets/16624784/12250322/45050ba8-b8c6-11e5-9359-e81909d0499e.jpg)

**Comment by jflann** [comment]
Not replicable, assumed fixed
