### ISSUE TITLE
RHW3 minicurve missing overrides

### ISSUE THREAD

**Issue by swordmasterSC4** [NAMTeam/Network-Addon-Mod#278]
![x](http://i.imgur.com/ApLJoTZ.jpg)

**Comment by TarkusSC4** [comment]
MRCs haven't been made for the RHW-3 yet (just the RHW-2, MIS, RHW-4, and RHW-6S), so this is really a case of a feature not yet being created.

**Comment by TarkusSC4** [comment]
Fixed with addition of RHW-3 MRCs for NAM 43.
