### ISSUE TITLE
Transit Stations SLURPed Improperly

### ISSUE THREAD

**Issue by zsc4** [NAMTeam/Network-Addon-Mod#279]
Robin recently discovered that several transit stations weren't being SLURPed properly.  Going from his results, I investigated further, and found that there are actually a fair number that fall into this category.  The reason that this problem didn't show up during testing is that it can only happen if the NSIS compiler is broken, and we had made the assumption that it was outputting correct code.  Furthermore, in the places we tested, the SLURPing process worked fine; it happens to work fine for most stations.  But for stations whose names are too long, it appears to trigger a buffer overrun bug in the NSIS compiler, and not all versions of the specified station are loaded into the installer executable.  This bug can get the compiler confused enough to get the compiler confused about the next station or two as well.  The result is that the wrong station may be loaded in the user's Station Overrides folder.  If the improper station is a DAMN station, and the user does not use DAMN, then the station is inaccessible, as these stations then have no menu entry for them.

This bug can be fixed without too much difficulty by rewriting part of the SLURP code in the installer so that the SLURPed station names are always short and use standard characters.

**Comment by TarkusSC4** [comment]
Since switching from NSIS to the Daeley Java installer, SLURP is no longer part of the NAM install, and we are still determining what all to do with SLURP going forward, as part of the reassembly of the MTA.
