### ISSUE TITLE
No L0 paths on DxO L2 RHW-8S intersections

### ISSUE THREAD

**Issue by woodb3kmasterSC4** [NAMTeam/Network-Addon-Mod#283]
Reported at SC4D by Alan_Waters [(here)](http://sc4devotion.com/forums/index.php?topic=1444.msg508964#msg508964). The innermost and outermost tiles on the diagonal L2 RHW-8S have no paths; the RHW doesn't need them on those tiles, but they're also lacking for the L0 vanilla networks. Not yet confirmed to affect other width/height combinations.

**Comment by woodb3kmasterSC4** [comment]
@TarkusSC4 found that the affected crossings have path files with an extra blank line that invalidates them in game. Affects 100+ path files with piece IDs 70-BC.

**Comment by TarkusSC4** [comment]
Fixed in late stages of NAM 35 development.
