### ISSUE TITLE
Missing Zoom 2-5 RHW textures for DTR overcrossings

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#302]
![image](https://user-images.githubusercontent.com/26899145/127671776-e9f5af64-0892-44fd-8ab5-cf5b2d083f22.png)

**Comment by jflann** [comment]
List of the missing textures:

5704000A-D
5705008A-D
5705000A-D
5706000A-D
5708008A-D
5708000A-D
5709000A-D

**Comment by TarkusSC4** [comment]
Looks like those fuzzy bridge textures were holding everything together.  Going to reprocess some lower zoom FSHes.

**Comment by TarkusSC4** [comment]
FSHes added.  Should be fixed with NAM 42 Build 08.
