### ISSUE TITLE
Opposing street WRCs blend override broken

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#315]
As reported by NAM team member Cheese

![image](https://user-images.githubusercontent.com/26899145/162618733-4003efa1-4da8-4e13-abd7-8ec823e88790.png)
![image](https://user-images.githubusercontent.com/26899145/162618741-1d6ae6b6-36b8-4f6d-8285-8f19f78ac5de.png)
![image](https://user-images.githubusercontent.com/26899145/162618747-92ed0dc3-ac35-4c7f-86f8-793dc30e2127.png)

Could be fixed with RUL2 but there is also possibly an INRUL solution which would also benefit the SAM variants

**Comment by h3ndofry** [comment]
@jflann this is an older issue, but I wonder how the behaviour of this is affected by the Diagonal Street helper puzzle pieces?

**Comment by jflann** [comment]
@h3ndofry AFAIK the helper pieces use actual diagonal flags whereas this is done using draggable diagonal streets with '2' flags.  The WRC is achieved with a side by side RUL2 override with a 0,0,0,0 tile.  I think this is inherently unstable.  The blend tile is an additional RUL2 override.

**Comment by jflann** [comment]
Closed, completed in #445 .
