### ISSUE TITLE
FA RRW pieces causing sinkhole bug

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#319]
As reported by cheese
![unknown-22](https://user-images.githubusercontent.com/26899145/175546339-d7786f29-9607-4600-9c70-0d0d4c4cbeba.png)
![unknown-27](https://user-images.githubusercontent.com/26899145/175546371-b0c7f7ff-59d9-48fc-b059-cd090f492000.png)

**Comment by LucarioBoricua** [comment]
Wouldn't the easier way to fix these be changing the "+" flags for "|" or "-" flags, as appropriate for the FA alignment?

**Comment by TarkusSC4** [comment]
> Wouldn't the easier way to fix these be changing the "+" flags for "|" or "-" flags, as appropriate for the FA alignment?

As of right now, there aren't any of the "+" flags that usually trigger this in the RUL0 definitions for these pieces.  They're mostly "-" flags from what I'm seeing.  I'm still kind of baffled as to why these are causing this issue.

**Comment by memo33** [comment]
It looks like the ConsLayout of the first piece (0xA368) might not be correctly centered, but shifted by one tile. The ConsLayout of the road crossing piece (0xA36B) is incorrectly mirrored along the horizontal axis. I just had a quick look.

**Comment by TarkusSC4** [comment]
Fixed by memo33's recent commit.
