### ISSUE TITLE
FLEX WT improperly converting RHW-4 to RHW-8S

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#326]
![image](https://user-images.githubusercontent.com/26899145/189482805-bbec61b3-0614-4190-94e2-36e7bed4cbc5.png)

**Comment by ulisse99** [comment]
The bug manifests itself in all directions

**Comment by jflann** [comment]
It would appear some side-by-side overrides of 57000000 are to blame.  Check for lines using this regex

`0x57710.00,[02],.,0x57000000,.,.,`  or '0x57000000,.,.,0x57710.00,[02],.'

Commenting these out seems to resolve the issue but potentially destabilizes the tile drop WTs and is worth looking at more closely.

**Comment by jflann** [comment]
Should be fixed via:

f9e00b5efc551b9d9e2dc103d77dc914885348bb

bebc8d4ca08cf00dc64fd53243243c963d18c6d3

309325f369da5b1dcba89f2221af81ba5b67f564
