### ISSUE TITLE
FLEX-WT Lane Drop from RHW-8S to RHW-6S produces outer 8S instead of RHW-6S (LHD)

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#327]
![image](https://user-images.githubusercontent.com/26899145/189486183-e4afe619-d966-4bb6-97c6-c791d871a078.png)

bug appears to affect only LHD based on rudimentary preliminary testing

**Comment by McDuell** [comment]
Using an RHD-based setup, there are no issues to be found. Dragging from top or bottom, in all directions, leads to a correct override.

![override_ok](https://user-images.githubusercontent.com/68449011/189486685-db90d994-0e9d-4e6a-b2e2-d76141175e45.jpg)

**Comment by jflann** [comment]
I believe these are the problematic lines - would fix but don't know exactly they ought to be

```
0x57754780,1,1,0x57000000,1,0=0x57756780,1,1,0x57050000,1,0
0x57754780,1,1,0x57000000,3,0=0x57756780,1,1,0x57050000,1,0
0x57745780,1,1,0x57000000,1,0=0x57765780,1,1,0x57050000,1,0
0x57745780,1,1,0x57000000,3,0=0x57765780,1,1,0x57050000,1,0

```

**Comment by jflann** [comment]
Should be fixed by the following:

849104c5e2ece941ed40592e74055fc6a2f51054

309325f369da5b1dcba89f2221af81ba5b67f564
