### ISSUE TITLE
OXD Slip Lane conflict with re-designed Road & OWR OXD intersections

### ISSUE THREAD

**Issue by LucarioBoricua** [NAMTeam/Network-Addon-Mod#344]
It seems the re-design of the Orthogonal X Diagonal intersections between Road and One-way broke down the override system used for the OXD slip lanes, otherwise formed by dragging a short OWR-2 segment on the acute angle sides of the OXD intersections. This affects intersections in which Road is the diagonal network.

![NAM 46 official - US RHD - Base Network Features - loss of support of OXD slip lanes](https://user-images.githubusercontent.com/88674871/212585453-6b892da5-c67d-4d60-a9d7-d1d4a18662ac.jpg)
![NAM 46 official - US RHD - Base Network Features - loss of support of OXD slip lanes - extra](https://user-images.githubusercontent.com/88674871/212585902-795214b9-8714-44af-9fdd-f82f0ec34a5d.jpg)

**Comment by jflann** [comment]
This seems to be the culprit:  bec5555a109acea1836a94c0fdf72a49dc72315b

![image](https://user-images.githubusercontent.com/26899145/212596690-de5eb430-3050-468d-a63e-fcdf987f5901.png)

**Comment by jflann** [comment]
Further review shows that 0x09703a00 only appears in a handful of lines in Sec1e_Rd_Misc and is not referenced anywhere else in the code

**Comment by jflann** [comment]
A couple more questions before I lose my train of thought -

What's the intended use case for x09703900 vs x09703a00?  Is one intended for T ints and the other for full +-ints?  If that's the case does there need to be a RUL1 definition for x09703a00? piece 39 alt for through?

`;piece 39
;
TYPE1=0x00030100,0x02000000,0x09703900,0,0
TYPE2=0x03010000,0x00000002,0x09703900,1,0
TYPE3=0x01000003,0x00000200,0x09703900,2,0
TYPE4=0x00000301,0x00020000,0x09703900,3,0
TYPE5=0x00000301,0x02000000,0x09703900,0,1
TYPE6=0x00030100,0x00000002,0x09703900,3,1
TYPE7=0x03010000,0x00000200,0x09703900,2,1
TYPE8=0x01000003,0x00020000,0x09703900,1,1
;
;piece 39 alt for through one-way
;
TYPE1=0x00030100,0x02000200,0x09703900,0,0
TYPE2=0x03010000,0x00020002,0x09703900,1,0
TYPE3=0x01000003,0x02000200,0x09703900,2,0
TYPE4=0x00000301,0x00020002,0x09703900,3,0
TYPE5=0x00000301,0x02000200,0x09703900,0,1
TYPE6=0x00030100,0x00020002,0x09703900,3,1
TYPE7=0x03010000,0x02000200,0x09703900,2,1
TYPE8=0x01000003,0x00020002,0x09703900,1,1`

Also, would it be possible to assign the diagonal T companion piece 0x09703c00 to RUL1 so as not to rely on RUL2?
