### ISSUE TITLE
Tile Drop FLEX-WT generates incorrect override

### ISSUE THREAD

**Issue by LucarioBoricua** [NAMTeam/Network-Addon-Mod#345]
The new tile-drop FLEX-WT piece generates a RHW-8S outer lanes override out of the end which should have RHW-6S, on the widening variant (US-RHD). Verification of LHD counterpart will be necessary.

![NAM 46 official - US RHD - RHW FLEX-WT - Tile Drop in-line WT spews RHW-8S outer lanes on narrow side of widening variant](https://user-images.githubusercontent.com/88674871/212586025-d8f657df-891e-42ae-9807-1518dad11f61.jpg)

**Comment by jflann** [comment]
LHD is working
![image](https://user-images.githubusercontent.com/26899145/212764036-5e0f5be4-0610-4653-89b0-ea778470a62a.png)
