### ISSUE TITLE
Bad override on RHW-8S Type D1 FLEXRamp

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#350]
![image](https://user-images.githubusercontent.com/26899145/214498061-6db950db-c758-4608-b078-e4431dc2d28c.png)

```
0x57040000,1,0,0x57813400,1,0=0x57040000,1,0,0x57853400,1,0
0x57040000,3,0,0x57813480,3,1=0x57040000,3,0,0x57853480,3,1
```
currently lines 7215-16
in 07_RHW/Sec7b_BaseNetwork/00_Orthogonal.txt

Don't know how to fix but tagging @TarkusSC4

**Comment by TarkusSC4** [comment]
8S tile drops to 6S are just a royal pain in the butt.  This almost looks like a wrong texture or a bad IID reference somewhere.  I'll take a look at this ramp in the coming days.
