### ISSUE TITLE
Interference between RHW 6C/8C A2 wide draggable ramp interface and L1 FLEX-OST

### ISSUE THREAD

**Issue by LucarioBoricua** [NAMTeam/Network-Addon-Mod#352]
The interference differs between the merging and the diverging variants of these ramps. It's possible the effects may be related to the recent re-design of the A2 and B2 merging ramps (adding the lane drop before merging).

When it's the merging variant, essentially all the tiles of the ramp branch revert to base RHW-4, rather than staying as the smooth curvature of the DRI.

Conversely, in the diverging variant, the override interference occurs in one tile, and only persists when the DRI and the FLEX-OST have no separation.

Advisable to verify this interference against the L2 FLEX-OST piece.

![NAM 46 official - US RHD - RHW draggable ramp interfaces - 8C-6C A2 wide ramp - interference with L1 OST - rigorous case verification](https://user-images.githubusercontent.com/88674871/215299339-848f161f-6364-44de-8cd5-6497686b6277.jpg)
![NAM 46 official - US RHD - RHW draggable ramp interfaces - 8C-6C A2 wide ramp - interference with L1 OST](https://user-images.githubusercontent.com/88674871/215299340-33f60964-a56b-4323-88f9-7e3638b626bd.jpg)

**Comment by LucarioBoricua** [comment]
As a follow-up verification, the RHW-10S / 8S A2 wide DRI also experiences the same bug. Meanwhile, it seems that the 8S/6S A2 wide variant isn't affected.

![NAM 46 official - US RHD - RHW draggable ramp interfaces - 10S-8S A2 wide ramp - interference with L1 OST - rigorous case verification](https://user-images.githubusercontent.com/88674871/215300510-bf66cf62-a431-4a2a-9ae7-84f17620323c.jpg)

**Comment by jflann** [comment]
I seemed to have fixed it, as far as I can tell.
