### ISSUE TITLE
NAM Lite - Maxis Highway connection bug

### ISSUE THREAD

**Issue by jpaulomotta** [NAMTeam/Network-Addon-Mod#373]
Hi,

Don't know if this issue belongs here.

I'm using the latest NAM Lite on top of vanilla sc4, in a fresh install.

As I was expanding the city's highway network I stumbled upon a problem. I was not able to connect the maxis ground highway with the elevated highway end-to-end.

The only possible connection was through the ```T``` where I'd drag ground highway into an elevated or vice-versa intersecting each other.

I wanted to do that to finish an elevated highway into a ground highway and then transition into an avenue.

It's been almost a decade since I played SC4 so I'm not 100% sure if this was possible to do on the base game. But the description on the highway tile says that I can drag it to the end of the other type of highway for a connection.

Here's a screenshot from the [docs](https://www.sc4nam.com/docs/feature-guides/maxis-highway-override/) on the transition I was expecting to use:
I know the docs on highway is using a very old version of NAM, it's just that I can't get a in-game screenshot atm. I will post later:

**Comment by TarkusSC4** [comment]
The screenshot confuses matters a little, because that's of Maxis Highway Override, which is not in NAM Lite and requires the full NAM.  There were some RUL issues that existed in NAM Lite 2 (some of the base Maxis RUL2 code was accidentally omitted), and it's possible this may have affected things.  I'll do an investigation on my end to see if this is indeed the case.  We do intend to compile a NAM Lite 3 at some point in the near future to address these issues, and potentially add a couple of small-scale features from the full NAM, which would not overload the Lite package.

**Comment by jpaulomotta** [comment]
Sorry, I couldn't take the screenshot when I opened the issue.

Just to clarify my setup is:

- SC4 Vanilla Steam edition
- NAM Lite 2

Here's what I was trying to do:

Can't connect elevated highway with ground highway
![image](https://user-images.githubusercontent.com/1813007/226071247-cf5e7f4b-5ff0-42a8-82ab-1c0651645fd2.png)

![image](https://user-images.githubusercontent.com/1813007/226071285-8c4d1025-54d3-4da6-9ad9-68b9deb65c92.png)

![image](https://user-images.githubusercontent.com/1813007/226071305-46b17eef-49a7-4736-b000-de9ec52bb46e.png)

Icon description saying I just need to drag to the end of the other type of highway to connect.
![image](https://user-images.githubusercontent.com/1813007/226071334-3ca8a391-0bb2-423a-b9fa-7929009464e2.png)

The reverse also applies (from elevated to ground).
![image](https://user-images.githubusercontent.com/1813007/226071374-b290ac29-adf4-4b0f-a17a-0eb0fce2eb54.png)

**Comment by jpaulomotta** [comment]
And thanks for looking into this.

You guys are doing an amazing job with NAM all these years!

🎉

**Comment by jpaulomotta** [comment]
@TarkusSC4 let me know if the pictures helped

**Comment by TarkusSC4** [comment]
I've finally gotten to compiling NAM Lite 3, and I can't replicate this issue with it, so it appears we're good.
