### ISSUE TITLE
Problems with D1 ramps

### ISSUE THREAD

**Issue by ulisse99** [NAMTeam/Network-Addon-Mod#375]
There are problems with the D1 Ramps. The first problem concerns that D1 ramps in the way they are placed. The problem manifests itself more with the following configuration

https://cdn.discordapp.com/attachments/900195208917032990/1091027005480390747/image.png

Dragging RHW 6S or 4S results in this effect

https://cdn.discordapp.com/attachments/900195208917032990/1091027093418168510/image.png

The external entrance ramp automatically becomes the exit ramp. This problem is manifested only by the entrance ramps parallel to each other. Exit ramps look fine

https://cdn.discordapp.com/attachments/900195208917032990/1091053451242389614/image.png

Second problem concerns the positioning of the ramp and its preview that are incorrect because the ramp is moved by a title with respect to the preview

**Comment by jflann** [comment]
Fixed by #380
