### ISSUE TITLE
Real Railway (RRW)

### ISSUE THREAD

**Issue by HernanKey** [NAMTeam/Network-Addon-Mod#401]
Real Railway (RRW), the viaducts lack the option to pass a train track over another train track in a single horizontal or vertical piece. There is the option about empty cells, about a diagonal train track and about the different types of paths, but this one is missing if it existed in a previous Nam... is there a way to obtain that missing file? 

Thank you so much and huge all you do.

- MacOS (either ARM or Intel x86)

**Comment by eggman121** [comment]
The main way to make overpasses has been edited to avoid the pathing issue with the direct Orthogonal X Diagonal Piece.

Also this adds functionality to the system in the way of slip switches.

The original setup can however be obtained by the drag pattern below

![Drag Pattern](https://github.com/NAMTeam/Network-Addon-Mod/assets/8378409/28dc9ab6-da0b-4896-b171-948e9e78760f)
![L2 DxO L0 RRW](https://github.com/NAMTeam/Network-Addon-Mod/assets/8378409/7a5ee487-d951-4af9-91a1-b024c1f4adef)

The L1 does not support this arrangement but does support the Flex Piece option in the Switches tab loop.

![RRW Flex Overpass](https://github.com/NAMTeam/Network-Addon-Mod/assets/8378409/086b8796-3961-4f86-855d-b972f521c6fa)

![RRW Flex Overpass Variety](https://github.com/NAMTeam/Network-Addon-Mod/assets/8378409/1b91f91b-eb61-4c71-a242-0d02af98b11c)

As shown above they can override to different directions.

**Comment by HernanKey** [comment]
Hi TarkusSC4 !!
Thank you very much for your prompt response. 
And sorry if I put it as a problem, I didn't know how to label it.

I have seen the diagonal of one track over another... 
but I am referring to the straight crossing of one over another.
My point is that what is missing (which was in previous MODs) is the crossing in the form of + (a horizontal path and a vertical one below)... 
I don't have a personal graph to send, but I am sending one that I found so you can see that I did it like this in my previous cities with the Previous mod... 
can that .dat be added somehow??
Thank you, thank you very much for the time and the answer.

![sc4 train overpasses train](https://github.com/NAMTeam/Network-Addon-Mod/assets/138070879/82701f03-8105-452c-9781-0bf7785581cc)
