### ISSUE TITLE
Incorrect override in RHW-8C Type E1 ramp.

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#402]
**Describe the bug**
Incorrect override produced in RHW-8C Type E1 ramp.  An entrance tile is present where an exit tile should be.

**To Reproduce**
1. Create RHW-8C E1 exit ramp, either through FLEXRamp, or DRI
2. Extend the 6C from the bottom of the ramp.
3. Observe error

**Expected behavior**
Should be exit texture

**Screenshots**
![image](https://github.com/NAMTeam/Network-Addon-Mod/assets/26899145/db1dd865-3f58-4c56-ba52-12d39e9ca18e)

**Additional context**
Does not appear to be any problem with the entrance version of the ramp.

**Comment by TarkusSC4** [comment]
Merged in pull request fixing this.
