### ISSUE TITLE
RHW-4 x Avenue long-T has a missing texture

### ISSUE THREAD

**Issue by sammibrie** [NAMTeam/Network-Addon-Mod#407]
**Describe the bug**
The "far" tile on the RHW-4 x Avenue long T is pathed with no texture.

**To Reproduce**
Construct an intersection as shown.

**Expected behavior**
There should be textures on both tiles.

**Screenshots**
![Screen_Shot_2023-07-10_at_16 45 34](https://github.com/NAMTeam/Network-Addon-Mod/assets/25447112/9eb48682-0a9c-4832-bb6c-5f7875371ab9)

**Desktop (please delete as appropriate):**
 - Windows

**Additional context**
Possible 44X-era issue?

**Comment by TarkusSC4** [comment]
Appears to be a missing EU texture at 0x57631305-9.  US texture .dat has it, and it's not an EU-specific texture, really, so it being a leftover from 44X is quite likely.  I've copied the texture over into the EU .dat, and inserted the new EU .dat into NAM 48 Build 02, so it should be fixed going forward.
