### ISSUE TITLE
SAM-2 x Lightrail (DxD) incorrect model

### ISSUE THREAD

**Issue by memo33** [NAMTeam/Network-Addon-Mod#478]
Zoom-5 correctly shows the SAM-2 texture, but zooms 1-4 show the Street texture instead.
![2024-05-02_21 15 59](https://github.com/NAMTeam/Network-Addon-Mod/assets/3751999/6eecc8ee-4dc0-45d4-9452-aa2a31cfe710)

**Comment by jflann** [comment]
This is fixed as of v49 build 02.  Your controller must be newer than your NAM install because the shadow mapping was added around the same time.

**Comment by memo33** [comment]
Oops, thanks for the fix.
