### ISSUE TITLE
draggable FAR particular setups

### ISSUE THREAD

**Issue by memo33** [NAMTeam/Network-Addon-Mod#71]
These are difficult to fix and have therefore been neglected for the time being.

![](http://img191.imageshack.us/img191/3081/screenshot001hx.jpg)
![](http://img401.imageshack.us/img401/1870/screenshot002ovn.jpg)
![](http://www.majhost.com/gallery/swm501/FAR/fa3_07.jpg)

**Comment by jflann** [comment]
stale
